---
minecraft_server: minecraft
minecraft_version: latest
minecraft_url: https://piston-data.mojang.com/v1/objects/c9df48efed58511cdd0213c56b9013a7b5c9ac1f/server.jar
minecraft_user: "{{ minecraft_server }}"
minecraft_group: "{{ minecraft_server }}"
minecraft_home: /srv/{{ minecraft_server }}
minecraft_max_memory: 1024M
minecraft_initial_memory: 1024M
minecraft_service_name: "{{ minecraft_server }}"
minecraft_supervisor_name: "{{ minecraft_service_name }}"