---
- name: enable service (systemd)
  service:
    name: "{{ minecraft_server_name }}.service"
    state: started
    enabled: true

- name: restarting the minecraft server
  service:
    name: "{{ minecraft_server_name }}.service"
    state: restarted