---
# handlers file for minecraft
- name: enable service (systemd)
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ minecraft_service_name }}.service"
    - "{{ minecraft_service_name }}.socket"
  when: minecraft_process_control == 'systemd'