---
- name: create Minecraft group
  group:
    state: present
    name: "{{ minecraft_group }}"
    system: yes

- name: create Minecraft user
  user:
    state: present
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_server_directory }}"

- name: Install required package
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10


- name: download Minecraft server
  get_url:
    url: "{{ minecraft_url }}"
    dest: "{{ minecraft_home }}/{{ minecraft_server_name }}.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0755'

- name: create minecraft server properties
  template:
    src: "minecraft.service.j2"
    destination: "{{minecraft_home}}/server.properties"
    user: 
    group: root
    mode: '0644'
  notify:
    - restart_minecraft

- name: create systemd service from template
  template:
    src: "minecraft.service.j2"
    destination: "/etc/systemd/system/{{ minecraft_server_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_minecraft
  register: systemd_service_config

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  when: systemd_service_config.changed
