---
- name: Testing if ansible invetory variable hostname is working
  hosts: all
  become: true
  gather_facts: true
  tasks: 
    - name: "Debug hostname"
      debug: msg="inventory_hostname={{ inventory_hostname }}, hostvars[inventory_hostname]['inventory_hostname']={{ hostvars[inventory_hostname]['inventory_hostname'] }}, ansible_hostname={{ ansible_hostname }}"
      ignore_errors: yes