---
- name: Setup my Ansible operator for easier login and more consistency
  hosts: ansible-testing
  become: true
  tasks: 

    - name: "Include role Containr.d"
      include_role:
        name: "containerd"