---
- name: Update UbuntuBased Machines
  hosts: all
  become: true
  tasks:
      - name: update / upgrade the machines (on Debian).
        ansible.builtin.apt:
          update_cache: true
          cache_valid_time: 3600
          upgrade: 'full'
        when: ansible_os_family == 'Debian'