---
- name: Install dependencies for default (worker) kubernetes node
  block:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Add kubernetes repostory key
      ansible.builtin.apt_key:
        url: "{{ kubernetes_repository_key }}"
        state: present

    - name: Add Kubernetes repository 
      ansible.builtin.apt_repository:
        repo: "{{ kubernetes_repository_path }}"
        state: present
        filename: 'kubernetes'

    - name: Install required package
      ansible.builtin.apt: 
        name: "{{ kubernetes_dependencys }}"
        state: present
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
      
  become: true
