---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu22.04
    image: ubuntu:22.04
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - destroy